version: "3"
services:
  db:
    image: mariadb
    restart: always
    volumes:
      - my_db:/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: test
      MYSQL_USER: test
      MYSQL_PASSWORD: test
    ports:
      - 3307:3306
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  my_db:
